version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile   
      target: prod   
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    container_name: nest_api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TZ: ${TZ}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      BACKUP_HOUR: ${BACKUP_HOUR}
      BACKUP_MIN: ${BACKUP_MIN}
      BACKUP_MONTH: ${BACKUP_MONTH}
      PORT: ${PORT}
      ACCOUNT_EMAIL: ${ACCOUNT_EMAIL}
      PASSWORD_EMAIL: ${PASSWORD_EMAIL}
      HOST_EMAIL: ${HOST_EMAIL}
      SECRET_KEY_JWT: ${SECRET_KEY_JWT}
      FRONTEND_URL: ${FRONTEND_URL}
      STRIPE_KEY: ${STRIPE_KEY}
      STRIPE_SUCESS_URL: ${STRIPE_SUCESS_URL}
      STRIPE_CANCEL_URL: ${STRIPE_CANCEL_URL}
      ACCOUNT_NAME_STORAGE: ${ACCOUNT_NAME_STORAGE}
      KEY_ACCOUNT_STORAGE: ${KEY_ACCOUNT_STORAGE}
      CONECTION_STRING_STORAGE: ${CONECTION_STRING_STORAGE}
      SETUP_INSIGN_AZURE: ${SETUP_INSIGN_AZURE}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db: 
    image: postgres:15
    restart: unless-stopped
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
